#   BUILD STAGE 1

FROM node:14.16.1 as node
WORKDIR /app
COPY package.json .
RUN npm install

COPY . .

RUN npm run build -- --configuration staging

# STAGE 2
FROM nginx:alpine
COPY --from=node /app/dist/odbui /usr/share/nginx/html
